added isCospiritUser in User
cospirit/front-component pull request #27
Opened 2022-03-17 11:18 UTC by gus3000

2022-03-22 09:40 UTC, lotholf approved these changes

2022-03-22 14:55 UTC, Jagagon approved these changes

2022-03-23 17:26 UTC, hightem requested changes

2022-03-23 17:26 UTC, hightem commented on modules/User.ts
> +            return (state.currentUser && state.currentUser.department);
```suggestion
            return (state.currentUser && !state.currentUser.internalAccount);
```

2022-03-23 17:26 UTC, hightem commented on modules/User.ts
> +            return (state.currentUser && state.currentUser.department);
il faudra aussi rajouter internalAccount à l'interface User plus haut dans le fichier

2022-03-29 13:10 UTC, lotholf approved these changes

2022-03-29 15:01 UTC, merged