Feature/integration univers
cospirit/front-component pull request #30
Opened 2022-05-06 10:08 UTC by gus3000

2022-05-17 13:23 UTC, lotholf requested changes

2022-05-17 13:23 UTC, lotholf commented on cospirit-api/OwnerMapper.ts
> +export default class OwnerMapper {
Spécifique également, à mettre directement dans le projet pour le moment

2022-05-17 13:23 UTC, lotholf commented on cospirit-api/Ptf/PtfFeature.ts
> +export default interface PtfFeature {
Spécifique à cockpit

2022-05-17 13:23 UTC, lotholf commented on cospirit-api/OwnerMapper.ts
> +                });
Peut être remplacé par `reduce()` pour éviter 2 parcours du tableau

2022-05-17 13:23 UTC, lotholf commented on universe/UniverseData.ts
> +import Entity from "./model/Entity";
Le front-component n'est pas l'endroit où ajouter ces définitions à mon avis.
Le service `universe-client` utilise déjà les données de `universe-client`. Il faut regarder si il n'y a pas possibilité de mutualiser ce genre de chose.

2022-05-17 14:21 UTC, gus3000 commented
TODO : rendre Universe.ts générique (genre API.ts), et faire en sorte que Http l'utilise et concentre le spécifique CospiritApi. Ensuite, déporter les mappers directement dans Cockpit (de manière à pouvoir les ressortir quand ils seront éprouvés). A voir avec @npiron où mettre les fonctionnalités semi-génériques comme celles-là

2022-06-08 08:41 UTC, gus3000 commented
> suggestion : reword les messages de certains commit comme TODO + accessoirement fixup (trop de commits (9))

Je pensais carrément faire un gros squash juste avant de merge, c'est plus propre comme ça

2022-06-08 08:51 UTC, lotholf approved these changes

2022-06-08 09:29 UTC, merged